version: '3.8'

services:
  postgres_db:
    image: postgres:16
    hostname: postgres
    restart: always
    container_name: verity-near-indexer-pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - xnfts-network
    volumes:
      - postgres-near-indexer:/var/lib/postgresql/data

  app:
    build:
      dockerfile: ./src/near_indexer/Dockerfile
      context: . 
    container_name: verity-near-indexer-app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RUST_LOG: debug
      RUST_BACKTRACE: 1
    networks:
      - xnfts-network
    depends_on:
      postgres_db:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "
        sea-orm-cli migrate up --migration-dir ./src/near_indexer/migration &&
        indexer
      "

  bitte_plugin:
    build:
      dockerfile: ./src/bitte_plugin/Dockerfile
      context: . 
    container_name: verity-near-bitte-app
    env_file:
      - ./src/bitte_plugin/.env
    ports:
      - "8007:8007"
    volumes:
      - .:/bitte_plugin
    command: >
          sh -c "bitte_plugin"
volumes:
  postgres-near-indexer:

networks:
  xnfts-network:
    driver: bridge
